import { Kysely, sql } from 'kysely';

/**
 * 015_client_type_and_payments
 *
 * Three additive changes, all nullable / defaulted so existing rows keep
 * working without backfill:
 *
 *   1. clients.client_type ∈ {'retail','wholesaler'}  default 'retail'
 *        — lets us segment the /admin/clients list into tabs and filter
 *          invoices by "wholesale" without faking it with tag strings.
 *
 *   2. PaymentMethod enum gains 'zelle' and 'venmo'
 *        — operators asked for these alongside cash/check for walk-ins.
 *          Adding to the column's CHECK constraint rather than a pg ENUM
 *          keeps the surface consistent with the rest of the schema,
 *          which uses CHECK'd text columns throughout.
 *
 *   3. invoices.payment_methods — JSONB array of
 *        [{method, reference, amount}] records so a single invoice can
 *        be split across cash + check, Zelle + cash, etc. The legacy
 *        `payment_method` column stays as the "primary" for PDF header
 *        and back-compat until the UI fully migrates.
 */
export async function up(db: Kysely<unknown>): Promise<void> {
  // --- 1. client_type ---
  await db.schema
    .alterTable('clients')
    .addColumn('client_type', 'text', (c) =>
      c.notNull().defaultTo('retail'),
    )
    .execute();

  await sql`
    ALTER TABLE clients
      ADD CONSTRAINT clients_client_type_chk
      CHECK (client_type IN ('retail','wholesaler'))
  `.execute(db);

  await db.schema
    .createIndex('clients_client_type_idx')
    .on('clients')
    .column('client_type')
    .execute();

  // --- 2. Extend PaymentMethod enum (CHECK constraint on text) ---
  // The existing constraint was defined with CHECK (payment_method IN
  // ('wire','check','ach','cash','crypto','card')). Drop + recreate it
  // with the two new methods allowed.
  //
  // Constraint names are generated by Postgres; we look them up from the
  // catalog rather than hard-coding in case the original migration renamed
  // it later. There should be exactly one CHECK on invoices.payment_method.
  await sql`
    DO $$
    DECLARE con_name text;
    BEGIN
      SELECT conname INTO con_name
      FROM pg_constraint
      WHERE conrelid = 'invoices'::regclass
        AND contype = 'c'
        AND pg_get_constraintdef(oid) LIKE '%payment_method%';
      IF con_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE invoices DROP CONSTRAINT %I', con_name);
      END IF;
    END $$;
  `.execute(db);

  await sql`
    ALTER TABLE invoices
      ADD CONSTRAINT invoices_payment_method_chk
      CHECK (payment_method IS NULL OR payment_method IN (
        'wire','check','ach','cash','crypto','card','zelle','venmo'
      ))
  `.execute(db);

  // --- 3. Multi-payment JSONB column on invoices ---
  await db.schema
    .alterTable('invoices')
    .addColumn('payment_methods', 'jsonb', (c) =>
      c.notNull().defaultTo(sql`'[]'::jsonb`),
    )
    .execute();
}

export async function down(db: Kysely<unknown>): Promise<void> {
  await db.schema.alterTable('invoices').dropColumn('payment_methods').execute();
  await sql`ALTER TABLE invoices DROP CONSTRAINT IF EXISTS invoices_payment_method_chk`.execute(db);
  await sql`
    ALTER TABLE invoices
      ADD CONSTRAINT invoices_payment_method_chk
      CHECK (payment_method IS NULL OR payment_method IN (
        'wire','check','ach','cash','crypto','card'
      ))
  `.execute(db);
  await db.schema.dropIndex('clients_client_type_idx').ifExists().execute();
  await sql`ALTER TABLE clients DROP CONSTRAINT IF EXISTS clients_client_type_chk`.execute(db);
  await db.schema.alterTable('clients').dropColumn('client_type').execute();
}
