import { Kysely, sql } from 'kysely';

/**
 * 034_shipments_multi_per_invoice
 *
 * Drops the 1:1 shipment-to-invoice constraint. Large wholesale orders
 * frequently ship in two or three boxes under separate tracking
 * numbers, and retail sends sometimes split between a secure-courier
 * insured piece and a regular padded-envelope piece. The old schema
 * made the operator cram multi-package sends into a single tracking
 * slot or manually maintain the extras out-of-band.
 *
 * Removing the UNIQUE(invoice_id) lets `shipments` be a 1-to-many
 * child of `invoices`, which is what the real-world workflow already
 * assumes. Notifications still fire per-shipment (each gets its own
 * tracking event), and the existing index on status is unaffected.
 *
 * The CONSTRAINT name in Postgres is auto-generated by Kysely's
 * `.unique()` call — it follows the pattern `<table>_<column>_key`.
 * Using IF EXISTS so the migration is idempotent if the environment
 * was rebuilt from a newer schema dump that never had the constraint.
 */
export async function up(db: Kysely<unknown>): Promise<void> {
  await sql`
    ALTER TABLE shipments
    DROP CONSTRAINT IF EXISTS shipments_invoice_id_key
  `.execute(db);

  // Add a non-unique index on invoice_id so the "fetch all shipments
  // for invoice X" query (used by the invoice-detail page) stays fast
  // as multi-shipment invoices accumulate. Fks are already indexed in
  // most Postgres configs, but belt-and-suspenders.
  await sql`
    CREATE INDEX IF NOT EXISTS shipments_invoice_id_idx
    ON shipments (invoice_id)
  `.execute(db);
}

export async function down(db: Kysely<unknown>): Promise<void> {
  await sql`
    DROP INDEX IF EXISTS shipments_invoice_id_idx
  `.execute(db);

  // Restore the unique constraint on rollback. Will fail if any invoice
  // has accumulated multiple shipments since the up() — that's the
  // intended signal to resolve data before rolling back.
  await sql`
    ALTER TABLE shipments
    ADD CONSTRAINT shipments_invoice_id_key UNIQUE (invoice_id)
  `.execute(db);
}
